version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - cinema:/var/lib/postgresql
volumes:
  cinema: